spring.application.name=employeecrud

server.servlet.context-path=/crud
server.port=8080

spring.datasource.url=jdbc:mysql://localhost/evaluacion?serverTimezone=America/Mexico_City
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Tresct1+

spring.jpa.hibernate.ddl-auto=none


spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jackson.time-zone=UTC